package com.CIMthetics.hwjvi.VulkanExtensions.VK11.Enums;

public enum VkAccelerationStructureTypeNV
{
    VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_NV(0),
    VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_NV(1),
    VK_ACCELERATION_STRUCTURE_TYPE_BEGIN_RANGE_NV(VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_NV.valueOf()),
    VK_ACCELERATION_STRUCTURE_TYPE_END_RANGE_NV(VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_NV.valueOf()),
    VK_ACCELERATION_STRUCTURE_TYPE_RANGE_SIZE_NV((VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_NV.valueOf() - VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_NV.valueOf() + 1)),
    VK_ACCELERATION_STRUCTURE_TYPE_MAX_ENUM_NV(0x7FFFFFFF);

    private int value;
    
    private VkAccelerationStructureTypeNV(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
