package com.CIMthetics.hwjvi.VulkanExtensions.VK11.Enums;

public enum VkBuildAccelerationStructureFlagBitsNV
{
    VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_NV(0x00000001),
    VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_NV(0x00000002),
    VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_NV(0x00000004),
    VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_NV(0x00000008),
    VK_BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_NV(0x00000010),
    VK_BUILD_ACCELERATION_STRUCTURE_FLAG_BITS_MAX_ENUM_NV(0x7FFFFFFF);

    private int value;
    
    private VkBuildAccelerationStructureFlagBitsNV(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
