package com.CIMthetics.hwjvi.VulkanExtensions.VK11.Enums;

public enum VkCopyAccelerationStructureModeNV
{
    VK_COPY_ACCELERATION_STRUCTURE_MODE_CLONE_NV(0),
    VK_COPY_ACCELERATION_STRUCTURE_MODE_COMPACT_NV(1),
    VK_COPY_ACCELERATION_STRUCTURE_MODE_BEGIN_RANGE_NV(VK_COPY_ACCELERATION_STRUCTURE_MODE_CLONE_NV.valueOf()),
    VK_COPY_ACCELERATION_STRUCTURE_MODE_END_RANGE_NV(VK_COPY_ACCELERATION_STRUCTURE_MODE_COMPACT_NV.valueOf()),
    VK_COPY_ACCELERATION_STRUCTURE_MODE_RANGE_SIZE_NV((VK_COPY_ACCELERATION_STRUCTURE_MODE_COMPACT_NV.valueOf() - VK_COPY_ACCELERATION_STRUCTURE_MODE_CLONE_NV.valueOf() + 1)),
    VK_COPY_ACCELERATION_STRUCTURE_MODE_MAX_ENUM_NV(0x7FFFFFFF);

    private int value;
    
    private VkCopyAccelerationStructureModeNV(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
