package com.CIMthetics.hwjvi.VulkanExtensions.VK11.Enums;

public enum VkCoarseSampleOrderTypeNV
{
    VK_COARSE_SAMPLE_ORDER_TYPE_DEFAULT_NV(0),
    VK_COARSE_SAMPLE_ORDER_TYPE_CUSTOM_NV(1),
    VK_COARSE_SAMPLE_ORDER_TYPE_PIXEL_MAJOR_NV(2),
    VK_COARSE_SAMPLE_ORDER_TYPE_SAMPLE_MAJOR_NV(3),
    VK_COARSE_SAMPLE_ORDER_TYPE_BEGIN_RANGE_NV(VK_COARSE_SAMPLE_ORDER_TYPE_DEFAULT_NV.valueOf()),
    VK_COARSE_SAMPLE_ORDER_TYPE_END_RANGE_NV(VK_COARSE_SAMPLE_ORDER_TYPE_SAMPLE_MAJOR_NV.valueOf()),
    VK_COARSE_SAMPLE_ORDER_TYPE_RANGE_SIZE_NV((VK_COARSE_SAMPLE_ORDER_TYPE_SAMPLE_MAJOR_NV.valueOf() - VK_COARSE_SAMPLE_ORDER_TYPE_DEFAULT_NV.valueOf() + 1)),
    VK_COARSE_SAMPLE_ORDER_TYPE_MAX_ENUM_NV(0x7FFFFFFF);

    private int value;
    
    private VkCoarseSampleOrderTypeNV(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
