package com.CIMthetics.hwjvi.VulkanExtensions.VK11.Enums;

public enum VkConservativeRasterizationModeEXT
{
    VK_CONSERVATIVE_RASTERIZATION_MODE_DISABLED_EXT(0),
    VK_CONSERVATIVE_RASTERIZATION_MODE_OVERESTIMATE_EXT(1),
    VK_CONSERVATIVE_RASTERIZATION_MODE_UNDERESTIMATE_EXT(2),
    VK_CONSERVATIVE_RASTERIZATION_MODE_BEGIN_RANGE_EXT(VK_CONSERVATIVE_RASTERIZATION_MODE_DISABLED_EXT.valueOf()),
    VK_CONSERVATIVE_RASTERIZATION_MODE_END_RANGE_EXT(VK_CONSERVATIVE_RASTERIZATION_MODE_UNDERESTIMATE_EXT.valueOf()),
    VK_CONSERVATIVE_RASTERIZATION_MODE_RANGE_SIZE_EXT((VK_CONSERVATIVE_RASTERIZATION_MODE_UNDERESTIMATE_EXT.valueOf() - VK_CONSERVATIVE_RASTERIZATION_MODE_DISABLED_EXT.valueOf() + 1)),
    VK_CONSERVATIVE_RASTERIZATION_MODE_MAX_ENUM_EXT(0x7FFFFFFF);

    private int value;
    
    private VkConservativeRasterizationModeEXT(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
