package com.CIMthetics.hwjvi.VulkanExtensions.VK11.Enums;

public enum VkMemoryOverallocationBehaviorAMD
{
    VK_MEMORY_OVERALLOCATION_BEHAVIOR_DEFAULT_AMD(0),
    VK_MEMORY_OVERALLOCATION_BEHAVIOR_ALLOWED_AMD(1),
    VK_MEMORY_OVERALLOCATION_BEHAVIOR_DISALLOWED_AMD(2),
    VK_MEMORY_OVERALLOCATION_BEHAVIOR_BEGIN_RANGE_AMD(VK_MEMORY_OVERALLOCATION_BEHAVIOR_DEFAULT_AMD.valueOf()),
    VK_MEMORY_OVERALLOCATION_BEHAVIOR_END_RANGE_AMD(VK_MEMORY_OVERALLOCATION_BEHAVIOR_DISALLOWED_AMD.valueOf()),
    VK_MEMORY_OVERALLOCATION_BEHAVIOR_RANGE_SIZE_AMD(VK_MEMORY_OVERALLOCATION_BEHAVIOR_DISALLOWED_AMD.valueOf() - VK_MEMORY_OVERALLOCATION_BEHAVIOR_DEFAULT_AMD.valueOf() + 1),
    VK_MEMORY_OVERALLOCATION_BEHAVIOR_MAX_ENUM_AMD(0x7FFFFFFF);

    private int value;
    
    private VkMemoryOverallocationBehaviorAMD(int value) { this.value = value; }
    
    public int valueOf() { return value; }

}
