package com.CIMthetics.hwjvi.VulkanExtensions.VK11.Enums;

public enum VkRayTracingShaderGroupTypeNV
{
    VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_NV(0),
    VK_RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_NV(1),
    VK_RAY_TRACING_SHADER_GROUP_TYPE_PROCEDURAL_HIT_GROUP_NV(2),
    VK_RAY_TRACING_SHADER_GROUP_TYPE_BEGIN_RANGE_NV(VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_NV.valueOf()),
    VK_RAY_TRACING_SHADER_GROUP_TYPE_END_RANGE_NV(VK_RAY_TRACING_SHADER_GROUP_TYPE_PROCEDURAL_HIT_GROUP_NV.valueOf()),
    VK_RAY_TRACING_SHADER_GROUP_TYPE_RANGE_SIZE_NV(VK_RAY_TRACING_SHADER_GROUP_TYPE_PROCEDURAL_HIT_GROUP_NV.valueOf() - VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_NV.valueOf() + 1),
    VK_RAY_TRACING_SHADER_GROUP_TYPE_MAX_ENUM_NV(0x7FFFFFFF);

    private int value;
    
    private VkRayTracingShaderGroupTypeNV(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
