package com.CIMthetics.hwjvi.VulkanExtensions.VK11.Enums;

public enum VkValidationFeatureDisableEXT
{
    VK_VALIDATION_FEATURE_DISABLE_ALL_EXT(0),
    VK_VALIDATION_FEATURE_DISABLE_SHADERS_EXT(1),
    VK_VALIDATION_FEATURE_DISABLE_THREAD_SAFETY_EXT(2),
    VK_VALIDATION_FEATURE_DISABLE_API_PARAMETERS_EXT(3),
    VK_VALIDATION_FEATURE_DISABLE_OBJECT_LIFETIMES_EXT(4),
    VK_VALIDATION_FEATURE_DISABLE_CORE_CHECKS_EXT(5),
    VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT(6),
    VK_VALIDATION_FEATURE_DISABLE_BEGIN_RANGE_EXT(VK_VALIDATION_FEATURE_DISABLE_ALL_EXT.valueOf()),
    VK_VALIDATION_FEATURE_DISABLE_END_RANGE_EXT(VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT.valueOf()),
    VK_VALIDATION_FEATURE_DISABLE_RANGE_SIZE_EXT(VK_VALIDATION_FEATURE_DISABLE_UNIQUE_HANDLES_EXT.valueOf() - VK_VALIDATION_FEATURE_DISABLE_ALL_EXT.valueOf() + 1),
    VK_VALIDATION_FEATURE_DISABLE_MAX_ENUM_EXT(0x7FFFFFFF);

    private int value;
    
    private VkValidationFeatureDisableEXT(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
