package com.CIMthetics.hwjvi.VulkanExtensions.VK11.Enums;

public enum VkValidationFeatureEnableEXT
{
    VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT(0),
    VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT(1),
    VK_VALIDATION_FEATURE_ENABLE_BEGIN_RANGE_EXT(VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT.valueOf()),
    VK_VALIDATION_FEATURE_ENABLE_END_RANGE_EXT(VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT.valueOf()),
    VK_VALIDATION_FEATURE_ENABLE_RANGE_SIZE_EXT(VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_RESERVE_BINDING_SLOT_EXT.valueOf() - VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT.valueOf() + 1),
    VK_VALIDATION_FEATURE_ENABLE_MAX_ENUM_EXT(0x7FFFFFFF);

    private int value;
    
    private VkValidationFeatureEnableEXT(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
