/*
 * Copyright 2019 Douglas Kaip
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.CIMthetics.jvulkan.VulkanCore.Enums;

public enum VkFormatFeatureFlagBits
{
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT(0x00000001),
    VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT(0x00000002),
    VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT(0x00000004),
    VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT(0x00000008),
    VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT(0x00000010),
    VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT(0x00000020),
    VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT(0x00000040),
    VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT(0x00000080),
    VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT(0x00000100),
    VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT(0x00000200),
    VK_FORMAT_FEATURE_BLIT_SRC_BIT(0x00000400),
    VK_FORMAT_FEATURE_BLIT_DST_BIT(0x00000800),
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT(0x00001000),
    VK_FORMAT_FEATURE_TRANSFER_SRC_BIT(0x00004000),
    VK_FORMAT_FEATURE_TRANSFER_DST_BIT(0x00008000),
    VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT(0x00020000),
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT(0x00040000),
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT(0x00080000),
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT(0x00100000),
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT(0x00200000),
    VK_FORMAT_FEATURE_DISJOINT_BIT(0x00400000),
    VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT(0x00800000),
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_IMG(0x00002000),
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT_EXT(0x00010000),
    VK_FORMAT_FEATURE_FRAGMENT_DENSITY_MAP_BIT_EXT(0x01000000),
    VK_FORMAT_FEATURE_TRANSFER_SRC_BIT_KHR(VK_FORMAT_FEATURE_TRANSFER_SRC_BIT.valueOf()),
    VK_FORMAT_FEATURE_TRANSFER_DST_BIT_KHR(VK_FORMAT_FEATURE_TRANSFER_DST_BIT.valueOf()),
    VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT_KHR(VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT.valueOf()),
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT_KHR(VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT.valueOf()),
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT_KHR(VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT.valueOf()),
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT_KHR(VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT.valueOf()),
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT_KHR(VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT.valueOf()),
    VK_FORMAT_FEATURE_DISJOINT_BIT_KHR(VK_FORMAT_FEATURE_DISJOINT_BIT.valueOf()),
    VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT_KHR(VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT.valueOf()),
    VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_EXT(VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_IMG.valueOf()),
    VK_FORMAT_FEATURE_FLAG_BITS_MAX_ENUM(0x7FFFFFFF);

    private int value;
    
    private VkFormatFeatureFlagBits(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
