package com.CIMthetics.hwjvi.VulkanCore.VK11.Enums;

public enum VkCoverageModulationModeNV
{
    VK_COVERAGE_MODULATION_MODE_NONE_NV(0),
    VK_COVERAGE_MODULATION_MODE_RGB_NV(1),
    VK_COVERAGE_MODULATION_MODE_ALPHA_NV(2),
    VK_COVERAGE_MODULATION_MODE_RGBA_NV(3),
    VK_COVERAGE_MODULATION_MODE_BEGIN_RANGE_NV(VK_COVERAGE_MODULATION_MODE_NONE_NV.valueOf()),
    VK_COVERAGE_MODULATION_MODE_END_RANGE_NV(VK_COVERAGE_MODULATION_MODE_RGBA_NV.valueOf()),
    VK_COVERAGE_MODULATION_MODE_RANGE_SIZE_NV((VK_COVERAGE_MODULATION_MODE_RGBA_NV.valueOf() - VK_COVERAGE_MODULATION_MODE_NONE_NV.valueOf() + 1)),
    VK_COVERAGE_MODULATION_MODE_MAX_ENUM_NV(0x7FFFFFFF);

    private int value;
    
    private VkCoverageModulationModeNV(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
