package com.CIMthetics.hwjvi.VulkanCore.VK11.Enums;

public enum VkDescriptorUpdateTemplateType
{
    VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_DESCRIPTOR_SET(0),
    VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_PUSH_DESCRIPTORS_KHR(1),
    VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_DESCRIPTOR_SET_KHR(VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_DESCRIPTOR_SET.valueOf()),
    VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_BEGIN_RANGE(VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_DESCRIPTOR_SET.valueOf()),
    VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_END_RANGE(VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_DESCRIPTOR_SET.valueOf()),
    VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_RANGE_SIZE((VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_DESCRIPTOR_SET.valueOf() - VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_DESCRIPTOR_SET.valueOf() + 1)),
    VK_DESCRIPTOR_UPDATE_TEMPLATE_TYPE_MAX_ENUM(0x7FFFFFFF);

    private int value;
    
    private VkDescriptorUpdateTemplateType(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
