package com.CIMthetics.hwjvi.VulkanCore.VK11.Enums;

public enum VkExternalFenceHandleTypeFlagBits
{
    VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT(0x00000001),
    VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_BIT(0x00000002),
    VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT(0x00000004),
    VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT(0x00000008),
    VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT_KHR(VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT.valueOf()),
    VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_BIT_KHR(VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_BIT.valueOf()),
    VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_KHR(VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT.valueOf()),
    VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT_KHR(VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT.valueOf()),
    VK_EXTERNAL_FENCE_HANDLE_TYPE_FLAG_BITS_MAX_ENUM(0x7FFFFFFF);

    private int value;
    
    private VkExternalFenceHandleTypeFlagBits(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
