package com.CIMthetics.hwjvi.VulkanCore.VK11.Enums;

public enum VkObjectEntryTypeNVX
{
    VK_OBJECT_ENTRY_TYPE_DESCRIPTOR_SET_NVX(0),
    VK_OBJECT_ENTRY_TYPE_PIPELINE_NVX(1),
    VK_OBJECT_ENTRY_TYPE_INDEX_BUFFER_NVX(2),
    VK_OBJECT_ENTRY_TYPE_VERTEX_BUFFER_NVX(3),
    VK_OBJECT_ENTRY_TYPE_PUSH_CONSTANT_NVX(4),
    VK_OBJECT_ENTRY_TYPE_BEGIN_RANGE_NVX(VK_OBJECT_ENTRY_TYPE_DESCRIPTOR_SET_NVX.valueOf()),
    VK_OBJECT_ENTRY_TYPE_END_RANGE_NVX(VK_OBJECT_ENTRY_TYPE_PUSH_CONSTANT_NVX.valueOf()),
    VK_OBJECT_ENTRY_TYPE_RANGE_SIZE_NVX((VK_OBJECT_ENTRY_TYPE_PUSH_CONSTANT_NVX.valueOf() - VK_OBJECT_ENTRY_TYPE_DESCRIPTOR_SET_NVX.valueOf() + 1)),
    VK_OBJECT_ENTRY_TYPE_MAX_ENUM_NVX(0x7FFFFFFF);

    private int value;
    
    private VkObjectEntryTypeNVX(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
