package com.CIMthetics.hwjvi.VulkanCore.VK11.Enums;

public enum VkPeerMemoryFeatureFlagBits
{
    VK_PEER_MEMORY_FEATURE_COPY_SRC_BIT(0x00000001),
    VK_PEER_MEMORY_FEATURE_COPY_DST_BIT(0x00000002),
    VK_PEER_MEMORY_FEATURE_GENERIC_SRC_BIT(0x00000004),
    VK_PEER_MEMORY_FEATURE_GENERIC_DST_BIT(0x00000008),
    VK_PEER_MEMORY_FEATURE_COPY_SRC_BIT_KHR(VK_PEER_MEMORY_FEATURE_COPY_SRC_BIT.valueOf()),
    VK_PEER_MEMORY_FEATURE_COPY_DST_BIT_KHR(VK_PEER_MEMORY_FEATURE_COPY_DST_BIT.valueOf()),
    VK_PEER_MEMORY_FEATURE_GENERIC_SRC_BIT_KHR(VK_PEER_MEMORY_FEATURE_GENERIC_SRC_BIT.valueOf()),
    VK_PEER_MEMORY_FEATURE_GENERIC_DST_BIT_KHR(VK_PEER_MEMORY_FEATURE_GENERIC_DST_BIT.valueOf()),
    VK_PEER_MEMORY_FEATURE_FLAG_BITS_MAX_ENUM(0x7FFFFFFF);

    private int value;
    
    private VkPeerMemoryFeatureFlagBits(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
