package com.CIMthetics.hwjvi.VulkanCore.VK11.Enums;

public enum VkPipelineCreateFlagBits
{
    VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT(0x00000001),
    VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT(0x00000002),
    VK_PIPELINE_CREATE_DERIVATIVE_BIT(0x00000004),
    VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT(0x00000008),
    VK_PIPELINE_CREATE_DISPATCH_BASE(0x00000010),
    VK_PIPELINE_CREATE_DEFER_COMPILE_BIT_NV(0x00000020),
    VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT_KHR(VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT.valueOf()),
    VK_PIPELINE_CREATE_DISPATCH_BASE_KHR(VK_PIPELINE_CREATE_DISPATCH_BASE.valueOf()),
    VK_PIPELINE_CREATE_FLAG_BITS_MAX_ENUM(0x7FFFFFFF);

    private int value;
    
    private VkPipelineCreateFlagBits(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
