package com.CIMthetics.hwjvi.VulkanCore.VK11.Enums;

public enum VkPointClippingBehavior
{
    VK_POINT_CLIPPING_BEHAVIOR_ALL_CLIP_PLANES(0),
    VK_POINT_CLIPPING_BEHAVIOR_USER_CLIP_PLANES_ONLY(1),
    VK_POINT_CLIPPING_BEHAVIOR_ALL_CLIP_PLANES_KHR(VK_POINT_CLIPPING_BEHAVIOR_ALL_CLIP_PLANES.valueOf()),
    VK_POINT_CLIPPING_BEHAVIOR_USER_CLIP_PLANES_ONLY_KHR(VK_POINT_CLIPPING_BEHAVIOR_USER_CLIP_PLANES_ONLY.valueOf()),
    VK_POINT_CLIPPING_BEHAVIOR_BEGIN_RANGE(VK_POINT_CLIPPING_BEHAVIOR_ALL_CLIP_PLANES.valueOf()),
    VK_POINT_CLIPPING_BEHAVIOR_END_RANGE(VK_POINT_CLIPPING_BEHAVIOR_USER_CLIP_PLANES_ONLY.valueOf()),
    VK_POINT_CLIPPING_BEHAVIOR_RANGE_SIZE((VK_POINT_CLIPPING_BEHAVIOR_USER_CLIP_PLANES_ONLY.valueOf() - VK_POINT_CLIPPING_BEHAVIOR_ALL_CLIP_PLANES.valueOf() + 1)),
    VK_POINT_CLIPPING_BEHAVIOR_MAX_ENUM(0x7FFFFFFF);

    private int value;
    
    private VkPointClippingBehavior(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
