package com.CIMthetics.hwjvi.VulkanCore.VK11.Enums;

public enum VkSamplerAddressMode
{
    VK_SAMPLER_ADDRESS_MODE_REPEAT(0),
    VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT(1),
    VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE(2),
    VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER(3),
    VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE(4),
    VK_SAMPLER_ADDRESS_MODE_BEGIN_RANGE(VK_SAMPLER_ADDRESS_MODE_REPEAT.valueOf()),
    VK_SAMPLER_ADDRESS_MODE_END_RANGE(VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER.valueOf()),
    VK_SAMPLER_ADDRESS_MODE_RANGE_SIZE((VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER.valueOf() - VK_SAMPLER_ADDRESS_MODE_REPEAT.valueOf() + 1)),
    VK_SAMPLER_ADDRESS_MODE_MAX_ENUM(0x7FFFFFFF);

    private int value;
    
    private VkSamplerAddressMode(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
