package com.CIMthetics.hwjvi.VulkanCore.VK11.Enums;

public enum VkSamplerYcbcrModelConversion
{
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY(0),
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY(1),
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709(2),
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601(3),
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020(4),
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY_KHR(VK_SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY.valueOf()),
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY_KHR(VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY.valueOf()),
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709_KHR(VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709.valueOf()),
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601_KHR(VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601.valueOf()),
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020_KHR(VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020.valueOf()),
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_BEGIN_RANGE(VK_SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY.valueOf()),
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_END_RANGE(VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020.valueOf()),
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_RANGE_SIZE((VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020.valueOf() - VK_SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY.valueOf() + 1)),
    VK_SAMPLER_YCBCR_MODEL_CONVERSION_MAX_ENUM(0x7FFFFFFF);

    private int value;
    
    private VkSamplerYcbcrModelConversion(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
