package com.CIMthetics.hwjvi.VulkanCore.VK11.Enums;

public enum VkTessellationDomainOrigin
{
    VK_TESSELLATION_DOMAIN_ORIGIN_UPPER_LEFT(0),
    VK_TESSELLATION_DOMAIN_ORIGIN_LOWER_LEFT(1),
    VK_TESSELLATION_DOMAIN_ORIGIN_UPPER_LEFT_KHR(VK_TESSELLATION_DOMAIN_ORIGIN_UPPER_LEFT.valueOf()),
    VK_TESSELLATION_DOMAIN_ORIGIN_LOWER_LEFT_KHR(VK_TESSELLATION_DOMAIN_ORIGIN_LOWER_LEFT.valueOf()),
    VK_TESSELLATION_DOMAIN_ORIGIN_BEGIN_RANGE(VK_TESSELLATION_DOMAIN_ORIGIN_UPPER_LEFT.valueOf()),
    VK_TESSELLATION_DOMAIN_ORIGIN_END_RANGE(VK_TESSELLATION_DOMAIN_ORIGIN_LOWER_LEFT.valueOf()),
    VK_TESSELLATION_DOMAIN_ORIGIN_RANGE_SIZE((VK_TESSELLATION_DOMAIN_ORIGIN_LOWER_LEFT.valueOf() - VK_TESSELLATION_DOMAIN_ORIGIN_UPPER_LEFT.valueOf() + 1)),
    VK_TESSELLATION_DOMAIN_ORIGIN_MAX_ENUM(0x7FFFFFFF);

    private int value;
    
    private VkTessellationDomainOrigin(int value) { this.value = value; }
    
    public int valueOf() { return value; }
}
